### ISSUE TITLE
Request: VYV Photon control

### ISSUE THREAD

**Issue by matthewcraigtaylor** [bitfocus/companion-module-vyv-photon#2]
Photon, has a similar feature set as D3. One way it beats D3 is the inbuilt cue(macro) system. Anything in the software can be recorded as a macro and executed as a cue. As such, when we externalise control, the simple way is to recall a cue within photon: it will do the rest. The manual lists many more parameters that can be externalised, but with the well implemented cue system I feel it is surplus to requirement. 

Companion is a wonderful piece of software to maximise the use of an inexpensive box. Thank you for the work you have put in.

**Comment by JeffreyDavidsz** [comment]
@matthewcraigtaylor Hi Matthew, seems we where sending `\r` and looking at your text it should be `\n`. I've changed that now, it will be in the latest build. Could you test that please?

**Comment by matthewcraigtaylor** [comment]
Jeffrey,
Many thanks for looking into this.  I think we are nearly there.  It is not yet working, but after testing and looking at the code in the module, it seems that it is written CUE_EXEC ID and then the ID.  It should instead send the ID number in place of 'ID'.
I have looked at the code with a friend and colleague and, if we have done it correctly, you should see a pull request waiting for you...  I hope.
Thank you again.
Matthew

**Comment by JeffreyDavidsz** [comment]
Ok I've merged your pull request. Please test it with a build (2.0)

**Comment by matthewcraigtaylor** [comment]
PERFECT!
It works a treat. Many thanks.

**Comment by JeffreyDavidsz** [comment]
Feel free to add additional commands and do a pull request!
