### ISSUE TITLE
Unhelpful implementation

### ISSUE THREAD

**Issue by bicciess** [bitfocus/companion-module-vyv-photon#5]
Hello!
The current module currently uses "CUE_EXEC" command, which will trigger a cue based on it's index. 
It would be far more helpful if this module used "CUE_EXEC_ID" which would trigger the cue based on it's ID. Within Photon, the user is easily able to find and manually change the ID for each cue. Therefore, this method would be a much more useful. At present, the user needs to try to workout which index number will trigger a specific cue. This is not something that is easy to find within Photon.

I have submitted a pull request a number of months ago which fixes this.

Photon's external TCP/UDP commands can be found here: https://docs.vyv.ca/step-by-step-tutorials-1/external-tcp-udp-control-specifications

**Comment by gotfox** [comment]
Agreed that "CUE_EXEC_ID" should be the implementation here.

**Comment by Julusian** [comment]
It looks like there is not currently a maintainer for this module, so unfortunately changes will be slow.
This has now been merged and will be in the 3.0 betas shortly
